# When does it happen
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    name: "Code Linting"
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: 'echo "hi!"'
      - name: step2
        run: 'echo "hi (again)!"'
