# When does it happen
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    name: "Code Linting"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone the repo"
        uses: actions/checkout@v4
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: "Install packages"
        run: "pip install -r requirements.txt"
      - name: Lint
        run: "pylint calculator/*.py"
